"""acousticbrainz_style_match_cache_and_stats

Revision ID: 8064a67142d0
Revises: ee6e2dd287ad
Create Date: 2026-08-12 03:08:55.795357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8064a67142d0'
down_revision: Union[str, Sequence[str], None] = 'ee6e2dd287ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_score_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_lo_id', sa.UUID(), nullable=False),
    sa.Column('profile_hi_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=20), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('breakdown', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_hi_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_lo_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_score_cache_computed_at'), 'match_score_cache', ['computed_at'], unique=False)
    op.create_index('ix_match_score_cache_current_pair', 'match_score_cache', ['profile_lo_id', 'profile_hi_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_index('ix_match_score_cache_hi_current', 'match_score_cache', ['profile_hi_id', 'is_current'], unique=False)
    op.create_index('ix_match_score_cache_lo_current', 'match_score_cache', ['profile_lo_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_match_score_cache_profile_hi_id'), 'match_score_cache', ['profile_hi_id'], unique=False)
    op.create_index(op.f('ix_match_score_cache_profile_lo_id'), 'match_score_cache', ['profile_lo_id'], unique=False)
    op.create_index(op.f('ix_match_score_cache_score'), 'match_score_cache', ['score'], unique=False)
    op.create_table('profile_match_stats',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('total_connections', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_projects_owned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_projects_joined', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cached_match_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_match_score', sa.Float(), nullable=True),
    sa.Column('top_match_profile_id', sa.UUID(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_match_stats')
    op.drop_index(op.f('ix_match_score_cache_score'), table_name='match_score_cache')
    op.drop_index(op.f('ix_match_score_cache_profile_lo_id'), table_name='match_score_cache')
    op.drop_index(op.f('ix_match_score_cache_profile_hi_id'), table_name='match_score_cache')
    op.drop_index('ix_match_score_cache_lo_current', table_name='match_score_cache')
    op.drop_index('ix_match_score_cache_hi_current', table_name='match_score_cache')
    op.drop_index('ix_match_score_cache_current_pair', table_name='match_score_cache', postgresql_where=sa.text('is_current'))
    op.drop_index(op.f('ix_match_score_cache_computed_at'), table_name='match_score_cache')
    op.drop_table('match_score_cache')
    # ### end Alembic commands ###
