"""canonical schema reconciling profiles connections projects orgs resources messages events language and privacy tables

Revision ID: ee6e2dd287ad
Revises: 
Create Date: 2026-08-12 02:39:01.592897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ee6e2dd287ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('discord_id', sa.String(length=64), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_by', sa.String(length=50), server_default='self', nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_requests_profile_id'), 'deletion_requests', ['profile_id'], unique=False)
    op.create_index(op.f('ix_deletion_requests_status'), 'deletion_requests', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('official', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_date'), 'events', ['date'], unique=False)
    op.create_index(op.f('ix_events_official'), 'events', ['official'], unique=False)
    op.create_table('language_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('definitions', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('drift_score', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('frequency_by_neurotype', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('frequency_by_location', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_entries_word'), 'language_entries', ['word'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('org_type', sa.String(length=50), nullable=True),
    sa.Column('roles_open', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('project_links', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('beta_info', sa.Text(), nullable=True),
    sa.Column('resume_request', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('trust_score', sa.Float(), server_default='0.5', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('discord_id', sa.String(length=64), nullable=False),
    sa.Column('discord_username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('links', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('neurotype', sa.String(length=20), nullable=True),
    sa.Column('offering', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('looking_for', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('projects', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('is_open', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.Column('vision_2036', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('badges', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('wall_posts', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_discord_id'), 'profiles', ['discord_id'], unique=True)
    op.create_index(op.f('ix_profiles_is_open'), 'profiles', ['is_open'], unique=False)
    op.create_index(op.f('ix_profiles_neurotype'), 'profiles', ['neurotype'], unique=False)
    op.create_table('quest_completions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('discord_id', sa.String(length=64), nullable=False),
    sa.Column('quest_key', sa.String(length=100), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('quest_metadata', sa.JSON(), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id', 'quest_key', name='_discord_quest_uc')
    )
    op.create_index(op.f('ix_quest_completions_discord_id'), 'quest_completions', ['discord_id'], unique=False)
    op.create_table('role_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('discord_id', sa.String(length=64), nullable=False),
    sa.Column('role_key', sa.String(length=100), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source', sa.String(length=50), server_default='onboarding', nullable=True),
    sa.Column('role_metadata', sa.JSON(), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id', 'role_key', name='_discord_role_uc')
    )
    op.create_index(op.f('ix_role_grants_discord_id'), 'role_grants', ['discord_id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_user_id', 'to_user_id', name='_from_to_uc')
    )
    op.create_index(op.f('ix_connections_from_user_id'), 'connections', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_connections_status'), 'connections', ['status'], unique=False)
    op.create_index(op.f('ix_connections_to_user_id'), 'connections', ['to_user_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('subject_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_profile_id'), 'consent_records', ['profile_id'], unique=False)
    op.create_table('deletion_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deletion_request_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('rows_affected', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deletion_request_id'], ['deletion_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_audit_log_deletion_request_id'), 'deletion_audit_log', ['deletion_request_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=True),
    sa.Column('to_user_id', sa.UUID(), nullable=True),
    sa.Column('from_user_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('to_user_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_from_user_id'), 'messages', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_messages_to_user_id'), 'messages', ['to_user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('owner_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('neurotypes_needed', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('skills_needed', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=True),
    sa.Column('votes', sa.Integer(), server_default='0', nullable=True),
    sa.Column('cool', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_category'), 'resources', ['category'], unique=False)
    op.create_index(op.f('ix_resources_status'), 'resources', ['status'], unique=False)
    op.create_index(op.f('ix_resources_type'), 'resources', ['type'], unique=False)
    op.create_table('project_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'profile_id', name='_project_profile_uc')
    )
    op.create_index(op.f('ix_project_participants_profile_id'), 'project_participants', ['profile_id'], unique=False)
    op.create_index(op.f('ix_project_participants_project_id'), 'project_participants', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_participants_project_id'), table_name='project_participants')
    op.drop_index(op.f('ix_project_participants_profile_id'), table_name='project_participants')
    op.drop_table('project_participants')
    op.drop_index(op.f('ix_resources_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_status'), table_name='resources')
    op.drop_index(op.f('ix_resources_category'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_messages_to_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_from_user_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_deletion_audit_log_deletion_request_id'), table_name='deletion_audit_log')
    op.drop_table('deletion_audit_log')
    op.drop_index(op.f('ix_consent_records_profile_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_connections_to_user_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_status'), table_name='connections')
    op.drop_index(op.f('ix_connections_from_user_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_role_grants_discord_id'), table_name='role_grants')
    op.drop_table('role_grants')
    op.drop_index(op.f('ix_quest_completions_discord_id'), table_name='quest_completions')
    op.drop_table('quest_completions')
    op.drop_index(op.f('ix_profiles_neurotype'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_is_open'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_discord_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_language_entries_word'), table_name='language_entries')
    op.drop_table('language_entries')
    op.drop_index(op.f('ix_events_official'), table_name='events')
    op.drop_index(op.f('ix_events_date'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_deletion_requests_status'), table_name='deletion_requests')
    op.drop_index(op.f('ix_deletion_requests_profile_id'), table_name='deletion_requests')
    op.drop_table('deletion_requests')
    # ### end Alembic commands ###
